version: "3.5"
services:
  tiny_test_log:
    image: tiny_test_log
    container_name: tiny_test_log
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /app
    entrypoint: ./tiny-server
    logging:
      driver: "json-file"
      options:
        max-size: "5K"
        max-file: "5"
